## SENSORS / LEGACY / HOUSE

# ALWAYS ON plugs
- platform: group
  name: 'Group Always On Plugs'
  all: true # group state should only turn on if all grouped entities are on
  entities:
    - switch.plg_crawlspace_3d_printer
    - switch.plg_crawlspace_deepfreezer
    - switch.plg_garage_fridge
    - switch.plg_laundry_washingmachine
