# Instructions on opening and wiring for flashing on https://blakadder.com/gl-s10

substitutions:
  device_name: bt-proxy-front
  device_description: "GL-iNet GL-S10"
  main_device_id: "bt_proxy_front" # Put the name that you want to see in Home Assistant.
  project_name: "esphome.bluetooth-proxy"
  project_version: "1.0"

esphome:
  name: ${device_name}
  comment: ${device_description}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}
  # turn on Power LED when esphome boots
  on_boot:
    then:
      - output.turn_on: power_led

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# VERSION 1.0
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
  manual_ip:
    static_ip: !secret bt_proxy_front_ip
    gateway: !secret network_gateway
    subnet: !secret network_subnet

api:
  encryption:
    key: !secret bt_proxy_front_key

logger:
  level: INFO # DEBUG for sensor readings

ota:
  - platform: esphome
    password: !secret bt_proxy_front_ota

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/gl-s10.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

## DEVICE SPECIFIC CONFIGURATION
# network LED (white one) configured as status led
status_led:
  pin:
    number: GPIO32
    inverted: true

# button on the side labeled RESET
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO33
      inverted: true
    name: "Reset Button"
# Bluetooth LED on when connected to Home Assistant
  - platform: status
    name: "${device_name} Status"
    internal: true
    on_press:
      - output.turn_on: bluetooth_led
    on_release:
      - output.turn_off: bluetooth_led

# output settings for LED's marked Power and Bluetooth
# power LED use: see code line 12
# bluetooth LED use: see code line 41
output:
  - platform: gpio
    pin: GPIO14
    inverted: true
    id: power_led
  - platform: gpio
    pin: GPIO12
    inverted: true
    id: bluetooth_led

# since these pins are broken out inside and labeled as I2C pins they're configured here
i2c:
  sda: 15
  scl: 13
  scan: true